apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: quarkusapp
  name: quarkusapp
  namespace: demo-pj
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/daytrader/quarkusapp:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
