apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: decision-service
  name: decision-service
  namespace: commons-demo
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: decision-service:latest
  postCommit: {}
  resources:
    limits:
      cpu: "4"
      memory: 7Gi
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/team-ohc-jp-place/commons-demo.git
    type: Git
    #contextDir: "quarkusapp"
  strategy:
    sourceStrategy:
      from:
        kind: "DockerImage"
        name: quay.io/quarkus/ubi-quarkus-native-s2i:20.1.0-java11
    type: Source
status:
  lastVersion: 0
