apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: decision-service
  name: decision-service
  namespace: commons-demo
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/commons-demo/decision-service:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
