apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  clientsCa:
    certificateExpirationPolicy: renew-certificate
  clusterCa:
    certificateExpirationPolicy: renew-certificate
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.8'
      inter.broker.protocol.version: '2.8'
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - authentication:
          type: tls
        name: external
        port: 9094
        tls: true
        type: route
    replicas: 3
    storage:
      type: ephemeral
    version: 2.8.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral