apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata: 
  name: earth-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      #- name: external
      #  port: 9094
      #  type: route
      #  tls: true
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}